CREATE TABLE `tb_user` (
  `user_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `hp` int(11) DEFAULT '50',
  `mp` int(11) DEFAULT '200',
  `ad` int(11) DEFAULT '5',
  `ap` int(11) DEFAULT '12',
  `max_hp` int(11) DEFAULT '50',
  `max_mp` int(11) DEFAULT '200',
  `str` int(11) DEFAULT '5',
  `int` int(11) DEFAULT '12',
  `fit` int(11) DEFAULT '2',
  `level` int(11) DEFAULT '1',
  `ap_point` int(11) DEFAULT '0',
  `exp` int(11) DEFAULT '0',
  `deleted` tinyint(2) DEFAULT '0',
  `acess_token` varchar(200) DEFAULT '',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `clear_dungeon` int(11) DEFAULT '0',
  PRIMARY KEY (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
